% This file contains parameters used to
%   1) Configure the scripts to the lab
%   2) Prepare labels for plotting
% ----------------------------------------
% LAB: EXAMPLE 2 LABORATORY
% ----------------------------------------


% =================================
% SECTION 1: LAB CONFIGURATION
% =================================


% 1a) Force Plate Naming Convention
% ---------------------------------------------------------------------
% Force plate numbers MUST be set up within the lab.
% The names of the channels of these force plates are defined here.
%       EXAMPLE
%       glab.FP.string = '%s%d%s';
%       glab.FP.prefix  = {'FP','FP','FP','FP','FP','FP'};
%       glab.FP.suffix  = {'Fx','Fy','Fz','Mx','My','Mz'};
%       
%       Moment about FP #3 in the X direction analog channel = 'FP3Mx'
%       Please note that the glab.FP.string IS CASE SENSITIVE
% 
%       verticalForceIndex is the index of the vertical GRF
%       (independant of direction) IN FORCE PLATE COORDINATES 
% 
%       glab.vertForceCutoff defines the vertical cutoff force (N),
%       above which a plate is deemed "active". Active plates together
%       with events are used to determine the foot-plate sequence.
% ---------------------------------------------------------------------
glab.FP.string = '%s%d%s';      % Prefix, PlateNum, Suffix

glab.FP.prefix  = {'Fx','Fy','Fz','Mx','My','Mz'};
glab.FP.suffix  = {'','','','','',''};

glab.FP.verticalForceIndex = 3;
glab.FP.filterOrder = 4;
glab.vertForceCutoff = 10;



% 1b) Coordinate Vector Setup
% ---------------------------------------------------------------------
% This section sets transformation vectors that are crucial to the
% rigid body transformations needed between the Force Plate, Vicon,
% and the Model coordinate systems.
% 
% Example: FP coord system -> Model coord system
%          glab.dirVec.FPMODEL(3,:)  = [2 -3 -1];   
% 
%          MODEL X = FP Y
%          MODEL Y = FP -Z
%          MODEL Z = FP -X
% ---------------------------------------------------------------------

% X direction (Vicon) Gait -> transformation vectors
glab.transform.VICMODEL(1,:) = [1 3 -2];     % Vicon coord system -> Model coord system

% -X direction (Vicon) Gait -> transformation vectors
glab.transform.VICMODEL(2,:) = [-1 3 2];   % Vicon coord system -> Model coord system

% Y direction (Vicon) Gait -> transformation vectors
glab.transform.VICMODEL(3,:) = [2 3 1];     % Vicon coord system -> Model coord system

% -Y direction (Vicon) Gait -> transformation vectors
glab.transform.VICMODEL(4,:) = [-2 3 -1];   % Vicon coord system -> Model coord system




% 1c) Special Markers
% ---------------------------------------------------------------------
% offsetMarker: marker to be used as the offset point to line up the
%               model to the walking platform in OpenSim. It is also
%               used to get the average speed in getEvents.
% 
% legLengthMarkers: a set of marker pairs that define the start and
%                   end of the leg to define leg length.
% ---------------------------------------------------------------------
glab.offsetMarker = 'SACR';
glab.legLengthMarkers = {'RASI', 'RLMAL', 'LASI', 'LLMAL'};




% 1d) Joint names used in OpenSim
% ---------------------------------------------------------------------
% Set this corresponding to the joint names in the OpenSim model
% Currently the joint label is only used to get create the coordinates
% file in getKinetics.m
% ---------------------------------------------------------------------
glab.jointModel = 'jointArms37';          % Joint convension
glab.muscleModel = 'musc92';              % Muscle convension




% 1e) Directory to store toolbox outputs
% ---------------------------------------------------------------------
% Output images, mat files, and text files from toolbox function calls
% can be stored in this directory for future reference. Must have
% a backslash at the end. i.e. '.\MyDir\'. This functionality is
% toggled by glab.storeInfo (1 = on, 0 = off)
% ---------------------------------------------------------------------
glab.storeInfo = 1;
glab.infoDirectory = '.\GaitExtract\';




% =================================
% SECTION 2: DATA EXTRACTION
% =================================


% 2a) Title Labels
% ---------------------------------------------------------------------
glab.name{1} = 'GRF';
glab.name{2} = 'CoP';
glab.name{3} = 'GRMo';
glab.name{4} = 'GRMx';
glab.name{5} = 'Joint Angles';
glab.name{6} = 'Joint Torques';
glab.name{7} = 'Muscle Forces';
glab.name{8} = 'EMG';




% GRF Direction Labels
% (x dir+-, y dir+-, z dir+-)
% ---------------------------------------------------------------------
glab.dir{1} = {'Fore',     'Aft'};
glab.dir{2} = {'Vertical', ''};
glab.dir{3} = {'Lateral',  'Medial'};




% GRF Labels
% (label, units, directionSign+, directionSign-)
% ---------------------------------------------------------------------
glab.S{1} = [{'GRF X (right)', 'N'}, glab.dir{1}(1), glab.dir{1}(2)];
glab.S{2} = [{'GRF Y (right)', 'N'}, glab.dir{2}(1), glab.dir{2}(2)];
glab.S{3} = [{'GRF Z (right)', 'N'}, glab.dir{3}(1), glab.dir{3}(2)];
glab.S{4} = [{'GRF X (left)',  'N'}, glab.dir{1}(1), glab.dir{1}(2)];
glab.S{5} = [{'GRF Y (left)',  'N'}, glab.dir{2}(1), glab.dir{2}(2)];
glab.S{6} = [{'GRF Z (left)',  'N'}, glab.dir{3}(1), glab.dir{3}(2)];




% CoP Labels
% (label, units, directionSign+, directionSign-)
% ---------------------------------------------------------------------
glab.X{1} = [{'CoP X (right)', 'm'}, glab.dir{1}(1), glab.dir{1}(2)];
glab.X{2} = [{'CoP Y (right)', 'm'}, glab.dir{2}(1), glab.dir{2}(2)];
glab.X{3} = [{'CoP Z (right)', 'm'}, glab.dir{3}(1), glab.dir{3}(2)];
glab.X{4} = [{'CoP X (left)',  'm'}, glab.dir{1}(1), glab.dir{1}(2)];
glab.X{5} = [{'CoP Y (left)',  'm'}, glab.dir{2}(1), glab.dir{2}(2)];
glab.X{6} = [{'CoP Z (left)',  'm'}, glab.dir{3}(1), glab.dir{3}(2)];




% GRM Labels (Origin)
% (label, units, directionSign+, directionSign-)
% ---------------------------------------------------------------------
glab.Mo{1} = [{'GRMo X (right)', 'Nm'}, glab.dir{1}(1), glab.dir{1}(2)];
glab.Mo{2} = [{'GRMo Y (right)', 'Nm'}, glab.dir{2}(1), glab.dir{2}(2)];
glab.Mo{3} = [{'GRMo Z (right)', 'Nm'}, glab.dir{3}(1), glab.dir{3}(2)];
glab.Mo{4} = [{'GRMo X (left)',  'Nm'}, glab.dir{1}(1), glab.dir{1}(2)];
glab.Mo{5} = [{'GRMo Y (left)',  'Nm'}, glab.dir{2}(1), glab.dir{2}(2)];
glab.Mo{6} = [{'GRMo Z (left)',  'Nm'}, glab.dir{3}(1), glab.dir{3}(2)];




% GRM Labels (CoP)
% (label, units, directionSign+, directionSign-)
% ---------------------------------------------------------------------
glab.Mx{1} = [{'GRMx X (right)', 'Nm'}, glab.dir{1}(1), glab.dir{1}(2)];
glab.Mx{2} = [{'GRMx Y (right)', 'Nm'}, glab.dir{2}(1), glab.dir{2}(2)];
glab.Mx{3} = [{'GRMx Z (right)', 'Nm'}, glab.dir{3}(1), glab.dir{3}(2)];
glab.Mx{4} = [{'GRMx X (left)',  'Nm'}, glab.dir{1}(1), glab.dir{1}(2)];
glab.Mx{5} = [{'GRMx Y (left)',  'Nm'}, glab.dir{2}(1), glab.dir{2}(2)];
glab.Mx{6} = [{'GRMx Z (left)',  'Nm'}, glab.dir{3}(1), glab.dir{3}(2)];




% Joint Labels
% (label, unitsAngle, unitsTorque)
% ---------------------------------------------------------------------
glab.jointArms37 = {{'pelvis_tx',         'm',   'N'}; ...
                    {'pelvis_ty',         'm',   'N'}; ...
                    {'pelvis_tz',         'm',   'N'}; ...
                    {'pelvis_list',       'deg', 'Nm'}; ...
                    {'pelvis_rotation',   'deg', 'Nm'}; ...
                    {'pelvis_tilt',       'deg', 'Nm'}; ...
                    {'hip_flexion_r',     'deg', 'Nm'}; ...
                    {'hip_adduction_r',   'deg', 'Nm'}; ...
                    {'hip_rotation_r',    'deg', 'Nm'}; ...
                    {'knee_angle_r',      'deg', 'Nm'}; ...
                    {'ankle_angle_r',     'deg', 'Nm'}; ...
                    {'subtalar_angle_r',  'deg', 'Nm'}; ...
                    {'mtp_angle_r',       'deg', 'Nm'}; ...
                    {'hip_flexion_l',     'deg', 'Nm'}; ...
                    {'hip_adduction_l',   'deg', 'Nm'}; ...
                    {'hip_rotation_l',    'deg', 'Nm'}; ...
                    {'knee_angle_l',      'deg', 'Nm'}; ...
                    {'ankle_angle_l',     'deg', 'Nm'}; ...
                    {'subtalar_angle_l',  'deg', 'Nm'}; ...
                    {'mtp_angle_l',       'deg', 'Nm'}; ...
                    {'lumbar_extension',  'deg', 'Nm'}; ...
                    {'lumbar_bending',    'deg', 'Nm'}; ...
                    {'lumbar_rotation',   'deg', 'Nm'}; ...
                    {'arm_flex_r',        'deg', 'Nm'}; ...
                    {'arm_add_r',         'deg', 'Nm'}; ...
                    {'arm_rot_r',         'deg', 'Nm'}; ...
                    {'elbow_flex_r',      'deg', 'Nm'}; ...
                    {'pro_sup_r',         'deg', 'Nm'}; ...
                    {'wrist_flex_r',      'deg', 'Nm'}; ...
                    {'wrist_dev_r',       'deg', 'Nm'}; ...
                    {'arm_flex_l',        'deg', 'Nm'}; ...
                    {'arm_add_l',         'deg', 'Nm'}; ...
                    {'arm_rot_l',         'deg', 'Nm'}; ...
                    {'elbow_flex_l',      'deg', 'Nm'}; ...
                    {'pro_sup_r',         'deg', 'Nm'}; ...
                    {'wrist_flex_r',      'deg', 'Nm'}; ...
                    {'wrist_dev_r',       'deg', 'Nm'}};





% Muscle Labels
% (muscle_name, spanning_joints)
% ---------------------------------------------------------------------
glab.musc92 = { {'glut_med1_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'glut_med2_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'glut_med3_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'glut_min1_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'glut_min2_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'glut_min3_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'semimem_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r', 'knee_angle_r'} ; ...
        {'semiten_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r', 'knee_angle_r'} ; ...
        {'bifemlh_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r', 'knee_angle_r'} ; ...
        {'bifemsh_r', 'knee_angle_r'} ; ...
        {'sar_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r', 'knee_angle_r'} ; ...
        {'add_long_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'add_brev_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'add_mag1_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'add_mag2_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'add_mag3_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'tfl_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r', 'knee_angle_r'} ; ...
        {'pect_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'grac_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r', 'knee_angle_r'} ; ...
        {'glut_max1_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'glut_max2_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'glut_max3_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'iliacus_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'psoas_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'quad_fem_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'gem_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'peri_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r'} ; ...
        {'rect_fem_r', 'hip_flexion_r', 'hip_adduction_r', 'hip_rotation_r', 'knee_angle_r'} ; ...
        {'vas_med_r', 'knee_angle_r'} ; ...
        {'vas_int_r', 'knee_angle_r'} ; ...
        {'vas_lat_r', 'knee_angle_r'} ; ...
        {'med_gas_r', 'knee_angle_r', 'ankle_angle_r'} ; ...
        {'lat_gas_r', 'knee_angle_r', 'ankle_angle_r'} ; ...
        {'soleus_r', 'ankle_angle_r'} ; ...
        {'tib_post_r', 'ankle_angle_r'} ; ...
        {'flex_dig_r', 'ankle_angle_r'} ; ...
        {'flex_hal_r', 'ankle_angle_r'} ; ...
        {'tib_ant_r', 'ankle_angle_r'} ; ...
        {'per_brev_r', 'ankle_angle_r'} ; ...
        {'per_long_r', 'ankle_angle_r'} ; ...
        {'per_tert_r', 'ankle_angle_r'} ; ...
        {'ext_dig_r', 'ankle_angle_r'} ; ...
        {'ext_hal_r', 'ankle_angle_r'} ; ...
        {'glut_med1_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'glut_med2_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'glut_med3_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'glut_min1_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'glut_min2_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'glut_min3_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'semimem_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l', 'knee_angle_l'} ; ...
        {'semiten_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l', 'knee_angle_l'} ; ...
        {'bifemlh_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l', 'knee_angle_l'} ; ...
        {'bifemsh_l', 'knee_angle_l'} ; ...
        {'sar_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l', 'knee_angle_l'} ; ...
        {'add_long_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'add_brev_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'add_mag1_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'add_mag2_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'add_mag3_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'tfl_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l', 'knee_angle_l'} ; ...
        {'pect_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'grac_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l', 'knee_angle_l'} ; ...
        {'glut_max1_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'glut_max2_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'glut_max3_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'iliacus_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'psoas_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'quad_fem_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'gem_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'peri_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l'} ; ...
        {'rect_fem_l', 'hip_flexion_l', 'hip_adduction_l', 'hip_rotation_l', 'knee_angle_l'} ; ...
        {'vas_med_l', 'knee_angle_l'} ; ...
        {'vas_int_l', 'knee_angle_l'} ; ...
        {'vas_lat_l', 'knee_angle_l'} ; ...
        {'med_gas_l', 'knee_angle_l', 'ankle_angle_l'} ; ...
        {'lat_gas_l', 'knee_angle_l', 'ankle_angle_l'} ; ...
        {'soleus_l', 'ankle_angle_l'} ; ...
        {'tib_post_l', 'ankle_angle_l'} ; ...
        {'flex_dig_l', 'ankle_angle_l'} ; ...
        {'flex_hal_l', 'ankle_angle_l'} ; ...
        {'tib_ant_l', 'ankle_angle_l'} ; ...
        {'per_brev_l', 'ankle_angle_l'} ; ...
        {'per_long_l', 'ankle_angle_l'} ; ...
        {'per_tert_l', 'ankle_angle_l'} ; ...
        {'ext_dig_l', 'ankle_angle_l'} ; ...
        {'ext_hal_l', 'ankle_angle_l'} ; ...
        {'ercspn_r', 'lumbar_extension', 'lumbar_bending', 'lumbar_rotation'} ; ...
        {'intobl_r', 'lumbar_extension', 'lumbar_bending', 'lumbar_rotation'} ; ...
        {'extobl_r', 'lumbar_extension', 'lumbar_bending', 'lumbar_rotation'}
        {'ercspn_l', 'lumbar_extension', 'lumbar_bending', 'lumbar_rotation'} ; ...
        {'intobl_l', 'lumbar_extension', 'lumbar_bending', 'lumbar_rotation'} ; ...
        {'extobl_l', 'lumbar_extension', 'lumbar_bending', 'lumbar_rotation'}};





% EMG Labels
% {label, name, associated muscles}
% note: associated muscle can take up any number of string cells
% Used by batchEMGprocess.m to know which EMG analog channels to
% extract from the C3D file
% ---------------------------------------------------------------------

% EMG set
% -------------------
glab.quadsEMG{1}  = {'Vastus Medialis'  ,'Vastus Medialis'};
glab.quadsEMG{2}  = {'Vastus Lateralis' ,'Vastus Lateralis'};
glab.quadsEMG{3}  = {'Rectus Femoris'   ,'Rectus Femoris'};





% EMG Processing Tasks
% {ProcessTask1, Value1, ProcessTask2, Value2, ...}
% notes: refer to processEMG.m for more information or type help processEMG
% 	     the operations are executed in order of appearance.
% ---------------------------------------------------------------------

glab.EMGprocessTKE1 = { 'tke', [], ...              % TKE filter
                        'rect', [], ...             % Rectification
                        'plot', 0 };                % Plot   
                    
glab.EMGprocessTKE2 = { 'tke', [], ...              % TKE filter
                        'rect', [], ...             % Rectification
                        'save', 1, ...              % Save plots
                        'hide', [], ...             % Hide raw/tke [1 2]
                        'plot', 1, ...              % Plot
                        'vertlines', 'C3Dkey'};     % Plot event lines

glab.EMGprocessFILTERS = { 'remdc', [], ...            % Remove DC Offset
                            'hpf', [4, 40], ...        % High Pass Filter
                            'rect', [], ...            % Rectification
                            'lpf', [4, 25], ...        % Low Pass Filter
                            'abovezero', [], ...       % Force EMG > 0
                            'plot', 1, ...             % Plot transformations
                            'vertlines', 'C3Dkey' };   % Plot event lines
                        
                        


% Kinematic Marker Set
% Used by getMarkers.m to know which markers to extract
% from the C3D file
% ---------------------------------------------------------------------
glab.markersDynamicArms = {'RSH', 'LSH', 'C7', ...                      % TORSO (5)
                      'LASI', 'RASI', 'SACR', ...                               % PELVIS (3)
                      'RTHAP', 'RTHAD', 'RTHLD', 'RTHLP', 'RLEPI', ... % RIGHT THIGH (6)
                      'RTIAP', 'RTIAD', 'RTILAT', 'RLMAL', ...         % RIGHT SHANK (5)
                      'RHEEL', 'RMFL', 'RMFS', 'RP1MT', 'RP5MT', 'RTOE', ... % RIGHT FOOT (6)
                      'RELB', 'RWR', ...                    % RIGHT ARM (4)
                      'LTHAP', 'LTHAD', 'LTHLD', 'LTHLP', 'LLEPI',  ... % LEFT THIGH (6)
                      'LTIAP', 'LTIAD', 'LTILAT', 'LLMAL', ...         % LEFT SHANK (5)
                      'LHEEL', 'LMFL', 'LMFS', 'LP1MT', 'LP5MT', 'LTOE', ... % LEFT FOOT (6)
                      'LELB', 'LWR'};                       % LEFT ARM (4)

glab.markersStaticArms = {'RSH', 'LSH', 'C7', ...                      % TORSO (5)
                      'LASI', 'RASI', 'SACR', ...                               % PELVIS (3)
                      'RTHAP', 'RTHAD', 'RTHLD', 'RTHLP', 'RLEPI', 'RMEPI', ... % RIGHT THIGH (6)
                      'RTIAP', 'RTIAD', 'RTILAT', 'RLMAL', 'RMMAL', ...         % RIGHT SHANK (5)
                      'RHEEL', 'RMFL', 'RMFS', 'RP1MT', 'RP5MT', 'RTOE', ... % RIGHT FOOT (6)
                      'RELB', 'RWR', ...                    % RIGHT ARM (4)
                      'LTHAP', 'LTHAD', 'LTHLD', 'LTHLP', 'LLEPI', 'LMEPI', ... % LEFT THIGH (6)
                      'LTIAP', 'LTIAD', 'LTILAT', 'LLMAL', 'LMMAL', ...         % LEFT SHANK (5)
                      'LHEEL', 'LMFL', 'LMFS', 'LP1MT', 'LP5MT', 'LTOE', ... % LEFT FOOT (6)
                      'LELB', 'LWR'};                       % LEFT ARM (4)
                   
